// <auto-generated />
using CoAPExplorer;
using CoAPExplorer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoAPExplorer.Database.Migrations
{
    [DbContext(typeof(CoapExplorerContext))]
    partial class CoapExplorerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("CoAPExplorer.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("EndpointType");

                    b.Property<bool>("IsFavourite");

                    b.Property<DateTime>("LastSeen");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CoAPExplorer.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Payload");

                    b.Property<string>("Url");

                    b.Property<string>("_dbCode")
                        .HasColumnName("Code");

                    b.Property<string>("_dbContentFormat")
                        .HasColumnName("ContentFormat");

                    b.Property<string>("_dbOptions")
                        .HasColumnName("Options");

                    b.HasKey("Id");

                    b.ToTable("RecentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
